[MOSIP-25631] Added reusable workflows
mosip/kattu pull request #2
Opened 2023-07-27 15:00 UTC by syedsalman3753

2023-08-01 14:00 UTC, gsasikumar requested changes

2023-08-07 09:17 UTC, ckm007 commented on .github/workflows/docker-build.yml
> +          docker build . --build-arg SOURCE=mosip --build-arg COMMIT_HASH=$(git rev-parse HEAD) --build-arg COMMIT_ID=$(git rev-parse --short HEAD) --build-arg BUILD_TIME=$BUILD_TIME --file Dockerfil
All the actiones performed by the reusable workflow applies on the caller workflow.
So, commit has also will be taken from caller. @syedsalman3753 then also please verify once before resolving the conversation.

2023-08-07 09:19 UTC, ckm007 commented on .github/workflows/helm-lint.yml
> +name: Lint and Test Charts
channel should be internal devops and devops.

2023-08-07 09:22 UTC, ckm007 commented
for all actions lets share a message to slack channel upon failures.
Make sure on failure slack is also configurable.
To differentiate in case of below mentioned repos share the failure message in both techleads as well as devops.
1. mosip-infra.
2. mosip-helm.
3. mosip-onboarder
4. postgres-init
5. keycloak-init
6. mosip-data
7. data-srchive

2023-08-08 11:28 UTC, ckm007 commented
Also lets add one workflow for one type of job. In the same job we can handle multiple callers relates cases in one workflow.
For e.g. Instead of having maven-sonar, gradel-sonar and npm-sonar. Lets have one workflow for sonar and then handle all these based upon condition and environment from there.

2023-08-21 11:16 UTC, syedsalman3753 commented on .github/workflows/docker-build.yml
> +          docker build . --build-arg SOURCE=mosip --build-arg COMMIT_HASH=$(git rev-parse HEAD) --build-arg COMMIT_ID=$(git rev-parse --short HEAD) --build-arg BUILD_TIME=$BUILD_TIME --file Dockerfil
Commit id are taken from caller workflow

2023-08-21 11:16 UTC, syedsalman3753 commented on .github/workflows/docker-build.yml
> +          fields: repo,message,commit,workflow,job # selectable (default: repo,message)
Added

2023-08-21 11:17 UTC, syedsalman3753 commented on .github/workflows/gradlew-publish-to-npm-registry.yml
> +name: Publish to NPM
renamed the workflow as requested

2023-08-21 11:18 UTC, syedsalman3753 commented on .github/workflows/npm-sonar-analysis.yml
> +      env:
Added slack alerts for all workflows

2023-08-21 11:20 UTC, syedsalman3753 commented on .github/workflows/helm-lint-manual.yml
> +name: Run Lint and Test Charts manually
Added slack alerts for all workflows

2023-08-21 11:26 UTC, syedsalman3753 commented on .github/workflows/helm-lint.yml
> +name: Lint and Test Charts
> channel should be internal devops and devops.

@ckm007 I have implemented the alert; kindly ensure that you update the GitHub secret labeled as `SLACK_DEVOPS_WEBHOOK`.

2023-08-21 12:48 UTC, syedsalman3753 commented on .github/workflows/gradlew-publish-to-npm-registry.yml
> +        run: cd ${{ inputs.SERVICE_LOCATION }} && npm publish
This is used to publish npm android applications to the npm registry

2023-08-21 13:09 UTC, syedsalman3753 commented
> for all actions lets share a message to slack channel upon failures. Make sure on failure slack is also configurable. To differentiate in case of below mentioned repos share the failure message in both techleads as well as devops.
> 
> 1. mosip-infra.
> 2. mosip-helm.
> 3. mosip-onboarder
> 4. postgres-init
> 5. keycloak-init
> 6. mosip-data
> 7. data-srchive

Added configuration to slack url

2023-08-21 13:10 UTC, syedsalman3753 commented
> Also lets add one workflow for one type of job. In the same job we can handle multiple callers relates cases in one workflow. For e.g. Instead of having maven-sonar, gradel-sonar and npm-sonar. Lets have one workflow for sonar and then handle all these based upon condition and environment from there.

@ckm007  As discussed, we will try this in the next round.

2023-08-21 13:25 UTC, syedsalman3753 commented on .github/workflows/gradlew-publish-to-npm-registry.yml
> +name: Publish to NPM
The developer has confirmed that it is necessary to build the application before its publication on the npm registry.

2023-08-22 08:19 UTC, ckm007 approved these changes

2023-08-22 12:01 UTC, gsasikumar approved these changes

2023-08-22 12:01 UTC, merged