[MOSIP-30161] Updated tag-readme.md
mosip/kattu pull request #44
Opened 2023-12-14 05:25 UTC by shubham17998

2023-12-14 13:06 UTC, syedsalman3753 approved these changes

2023-12-15 04:17 UTC, SwatiPeriwal requested changes
Minor change... pls review

2023-12-15 04:17 UTC, SwatiPeriwal commented on docs/tag-readme.md
> +    - `LATEST` : Set too false to prevent marking the release as the latest.
`LATEST` : Set to **false** to prevent marking the release as the latest.

2023-12-15 04:28 UTC, SwatiPeriwal approved these changes
Approved

2023-12-15 12:11 UTC, syedsalman3753 approved these changes

2023-12-15 13:56 UTC, ckm007 approved these changes

2023-12-15 13:56 UTC, merged